########################################################
# Libraries
########################################################
library(dplyr)
library(data.table)
library(MetBrewer)
library(ggplot2)
library(ggforestplot)
library(showtext)
font_add("Arial", "/System/Library/Fonts/Supplemental/Arial.ttf", bold = "/System/Library/Fonts/Supplemental/Arial Bold.ttf", italic = "/System/Library/Fonts/Supplemental/Arial Italic.ttf", bolditalic = "/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf")



########################################################
# STEP 1: Load data
########################################################

# Load phenotype-mediator pairs to test (generated by script/03_Mendelian_randomization/02_MR_forward_reverse_comparison.R)
df <- as.data.frame(fread("/data/MR/pairs_bidirectional_MR.txt"))

# Load MR data (generated by script/03_Mendelian_randomization/01_MR_pipeline) & subset IVW results
mr <- as.data.frame(fread("/data/MR/MR_merged_results.tsv"))


########################################################
# STEP 2: Extract MR data
########################################################

# Create an empty dataframe to store results
df_sensitivity <- data.frame()

# Extract MR data for relevant mediator-trait pairs
for (i in 1:nrow(df)) {
  
  # Define the mediator-trait pair
  p <- df[i, "PHENO_MR"]
  m <- df[i, "MEDIATOR_MR"]
  print(paste0("Analyzing the relation between ", df[i, "MEDIATOR"], " and ", df[i, "PHENO"]))
  
  # Extract the forward effect
  df_forward <- mr[which(mr$exposure == m & mr$outcome == p), c(1:3,5:7)]
  df_forward$DIRECTION <- "forward"
  df_forward$MEDIATOR <- df[i, "MEDIATOR"]
  df_forward$PHENO <- df[i, "PHENO"]
  df_sensitivity <- rbind(df_sensitivity, df_forward)
  rm(df_forward)
  
  # Extract the reverse effect
  df_reverse <- mr[which(mr$exposure == p & mr$outcome == m), c(1:3,5:7)]
  df_reverse$DIRECTION <- "reverse"
  df_reverse$MEDIATOR <- df[i, "MEDIATOR"]
  df_reverse$PHENO <- df[i, "PHENO"]
  df_sensitivity <- rbind(df_sensitivity, df_reverse)
  rm(df_reverse)

}

# Rename columns
colnames(df_sensitivity) <- c("EXPOSURE", "OUTCOME", "METHOD", "ALPHA", "SE", "P", "DIRECTION", "MEDIATOR", "PHENO")



########################################################
# STEP 3: Factorize
########################################################


# Factorize the MR direction
df_sensitivity$DIRECTION <- factor(df_sensitivity$DIRECTION, levels = c("forward", "reverse"))

# Set label (file with two columns: PHENO = short phenotype name used in above analyses; LABEL = phenotype name to be printed on the graph)
labels <- as.data.frame(fread("phenotype_labels.txt"))
df <- left_join(df, labels, by = "PHENO")

# Set size and transparency according to significance
df_sensitivity$SIG <- "no"
df_sensitivity[which(df_sensitivity$P <= 0.05/(2*nrow(df))), "SIG"] <- "yes"
df_sensitivity$SIG <- factor(df_sensitivity$SIG, levels = c("yes", "no"))

# Order phenotypes
ordered_pheno <- df_sensitivity[which(df_sensitivity$METHOD == "Inverse variance weighted" & df_sensitivity$DIRECTION == "forward"), ]
ordered_pheno <- ordered_pheno[order(ordered_pheno$ALPHA, decreasing = F), "LABEL"]
df_sensitivity$LABEL <- factor(df_sensitivity$LABEL, levels = unique(ordered_pheno))



########################################################
# STEP 4: Plot - Forest plot
########################################################

# Plot
p_sensitivity <- ggplot(data = df_sensitivity) +
                # Background
                geom_stripes(aes(y = LABEL), odd = "#F4F4F4", even = "white") + 
                geom_vline(xintercept = 0, color = "#2B4050", linewidth = 0.8, lty = "dashed") +
                # Effect
                geom_effect(aes(x = ALPHA, y = LABEL, xmin = ALPHA - 1.96*SE, xmax = ALPHA + 1.96*SE, colour = METHOD, alpha = SIG),
                            position = ggstance::position_dodgev(height = 0.5), size = 0.75) +
                scale_color_manual("MR effect", values = c(met.brewer("Java", 5)), drop = F) +
                scale_alpha_manual("Significant", values = c(1, 0.35), drop = F) +
                # Facet
                facet_grid(MEDIATOR~DIRECTION, scales = "free", space = "free", switch = "y") +
                scale_y_discrete(position = "right") +
                # Axis
                xlab("MR causal effect ± 95% CI") + ylab("") +
                coord_cartesian(xlim = c(-0.5, 0.8)) +
                # Layout
                theme_bw() +
                theme(text = element_text(family = "Arial"),
                      axis.text.x = element_text(size = 9),
                      axis.title.x = element_text(size = 12, margin = margin(t = 7, r = 0, b = 0, l = 0)),
                      axis.text.y = element_text(size = 11),
                      legend.title = element_text(size = 12, face = "bold"),
                      legend.text = element_text(size = 11),
                      legend.position = "left", 
                      strip.text.y.left = element_text(size = 11, color = "#2B4050", face = "bold",  angle = 0),
                      strip.text.x = element_text(size = 11, color = "#2B4050", face = "bold",  angle = 0),
                      strip.background = element_rect(fill = "#F4F4F4", color = "#2B4050")) +
                guides(colour = guide_legend(override.aes = list(size = 3))) +
                guides(alpha = guide_legend(override.aes = list(size = 3)))

# Save plot
showtext_auto()   
p_sensitivity
ggsave("/plot/MR_sensitivity.pdf", width = 12, height = 6)
showtext_auto(FALSE)