########################################################
# Libraries
########################################################
library(dplyr)
library(data.table)
library(ggplot2)
library(MetBrewer)
library(ggrepel)
library(ggsignif)
library(pixiedust)
library(gridExtra)
library(showtext)
font_add("Arial", "/System/Library/Fonts/Supplemental/Arial.ttf", bold = "/System/Library/Fonts/Supplemental/Arial Bold.ttf", italic = "/System/Library/Fonts/Supplemental/Arial Italic.ttf", bolditalic = "/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf")



########################################################
# STEP 1: Load data
########################################################

# Load sample file (vector with identifiers, with header "eid")
samples <- as.data.frame(fread("samples_white_british_All.txt", col.names = "eid"))

# Load CNV file and subset samples (output from CNV calling pipeline, as described in Auwerx et al., 2022 (AJHG))
cnvs <- as.data.frame(fread("ukb_cnv_global.gz"))
cnvs$Sample_Name <- sub("_.*", "", cnvs$Sample_Name)
cnvs <- cnvs[cnvs$Sample_Name %in% samples$eid, ]

# Load CNV carriers and subset those with at least 25 matched controls (files generated by script/04_matched_control/01_select_matched_controls.R)
dup_subset <- as.data.frame(fread("/data/case_control/controls_dup_min_25_count.txt")) 
dup_subset <- dup_subset[which(dup_subset$count >= 25), "IID"]
del_subset <- as.data.frame(fread("/data/case_control/controls_del_min_25_count.txt")) 
del_subset <- del_subset[which(del_subset$count >= 25), "IID"]

# Load continuous phenotype data (non-transformed; as described in Auwerx et al., 2022 (AJHG); identifier + 1 column/trait); 
# Sex-specific traits originate from sex-specific data files and are appended to the main dataframe
pheno_All <- as.data.frame(fread("pheno_continuous_WB_raw_All.txt.gz"))
pheno_M <- as.data.frame(fread("pheno_continuous_WB_raw_M.txt.gz"))
pheno_F <- as.data.frame(fread("pheno_continuous_WB_raw_F.txt.gz"))
pheno <- left_join(pheno_All, pheno_M[, names(pheno_M) %in% c("IID", "balding", "facial_hair")], by = "IID"); rm(pheno_All, pheno_M)
pheno <- left_join(pheno, pheno_F[, names(pheno_F) %in% c("IID", "menarche", "menopause", "birth_weight_first_child")], by = "IID"); rm(pheno_F)

# Load disease status data (identifier + 1 column/trait); 
# Sex-specific diseases originate from sex-specific data files and are appended to the main dataframe; 
# Data file is encoded so that cases are 1, controls are 0, and missing data NA
disease <- as.data.frame(fread("pheno_ICD10_All.txt.gz"))
disease[disease == 1] <- 0
disease[disease == 2] <- 1

# Load labels; This list contain the 23 traits that associate with the CNVs even after adjustment for BMI or EA and are not too correlated to the latter
# File created manually, which contains the following columns for each of the tested traits:
# PHENO: short phenotype name matching other dataframes;
# TITLE: plot title;
# Y-AXIS: label for the plot's y-axis;
# CAT: phenotype category (for color);
# TYPE: either "cont" or "disease", will determine which plot type is needed.
labels <- as.data.frame(fread("case_control_trait_labels.txt"))



########################################################
# STEP 2: Generate genotype table
########################################################

# Identify CNV carriers according to the following criteria; Distinguish deletion and duplication carriers;
# Start: 29.4-29.8 Mb; End: 30.05-30.4 Mb; |QS| > 0.5 
cnvs <- cnvs[which(cnvs$Chromosome == 16 & cnvs$Start_Position_bp >= 29400000 & cnvs$Start_Position_bp <= 29800000 & cnvs$End_Position_bp >= 30050000 & cnvs$End_Position_bp <= 30400000 & abs(cnvs$Quality_Score) >= 0.5), ]
dup_carriers <- as.numeric(cnvs[which(cnvs$Copy_Number > 2), "Sample_Name"])
del_carriers <- as.numeric(cnvs[which(cnvs$Copy_Number < 2), "Sample_Name"])

# Identify CNV carriers that are not in the matched-control subset (i.e., excluded from the analysis due to lack of data or matched controls)
dup_excluded <- dup_carriers[!dup_carriers %in% dup_subset]
del_excluded <- del_carriers[!del_carriers %in% del_subset]
rm(dup_carriers, del_carriers)



########################################################
# STEP 3: Loop over phenotypes
########################################################

### Continuous traits ##################################

# Create an empty dataframe to store t-test results for continuous traits
t_test_results <- data.frame(PHENO = labels[which(labels$TYPE == "cont"), "PHENO"], 
                             N_DUP_subset = NA, MEAN_DUP_subset = NA, SE_DUP_subset = NA, 
                             N_DUP_excluded = NA, MEAN_DUP_excluded = NA, SE_DUP_excluded = NA, 
                             P_DUP = NA,
                             N_DEL_subset = NA, MEAN_DEL_subset = NA, SE_DEL_subset = NA, 
                             N_DEL_excluded = NA, MEAN_DEL_excluded = NA, SE_DEL_excluded = NA, 
                             P_DEL = NA)

# Subset continuous phenotype dataframe by CNV type
pheno_dup_subset <- pheno[pheno$IID %in% dup_subset, ]
pheno_dup_excluded <- pheno[pheno$IID %in% dup_excluded, ]
pheno_del_subset <- pheno[pheno$IID %in% del_subset, ]
pheno_del_excluded <- pheno[pheno$IID %in% del_excluded, ]

# Loop over phenotypes to be tested
for (i in 1:nrow(t_test_results)) {
  
  # Define the phenotype
  p <- t_test_results[i, "PHENO"]
  print(paste0("Analyzing: ", p))
  
  # Fill in the table (Duplication)
  t_test_results[i, "N_DUP_subset"] <- length(na.omit(pheno_dup_subset[, p]))
  t_test_results[i, "MEAN_DUP_subset"] <- mean(na.omit(pheno_dup_subset[, p]))
  t_test_results[i, "SE_DUP_subset"] <- sd(na.omit(pheno_dup_subset[, p]))/sqrt(length(na.omit(pheno_dup_subset[, p])))
  t_test_results[i, "N_DUP_excluded"] <- length(na.omit(pheno_dup_excluded[, p]))
  t_test_results[i, "MEAN_DUP_excluded"] <- mean(na.omit(pheno_dup_excluded[, p]))
  t_test_results[i, "SE_DUP_excluded"] <- sd(na.omit(pheno_dup_excluded[, p]))/sqrt(length(na.omit(pheno_dup_excluded[, p])))
  t_test_results[i, "P_DUP"] <- t.test(na.omit(pheno_dup_subset[, p]), na.omit(pheno_dup_excluded[, p]), alternative = "two.sided")$p.value
  
  # Fill in the table (Deletion)
  t_test_results[i, "N_DEL_subset"] <- length(na.omit(pheno_del_subset[, p]))
  t_test_results[i, "MEAN_DEL_subset"] <- mean(na.omit(pheno_del_subset[, p]))
  t_test_results[i, "SE_DEL_subset"] <- sd(na.omit(pheno_del_subset[, p]))/sqrt(length(na.omit(pheno_del_subset[, p])))
  t_test_results[i, "N_DEL_excluded"] <- length(na.omit(pheno_del_excluded[,p ]))
  t_test_results[i, "MEAN_DEL_excluded"] <- mean(na.omit(pheno_del_excluded[, p]))
  t_test_results[i, "SE_DEL_excluded"] <- sd(na.omit(pheno_del_excluded[, p]))/sqrt(length(na.omit(pheno_del_excluded[, p])))
  t_test_results[i, "P_DEL"] <- t.test(na.omit(pheno_del_subset[, p]), na.omit(pheno_del_excluded[, p]), alternative = "two.sided")$p.value
  
}

# Save results 
fwrite(t_test_results, "/data/case_control/case_control_t_test_SUBSET_vs_EXCLUDED.txt", col.names = T, row.names = F, quote = F, sep = "\t")


### Diseases #####################################

# Create an empty dataframe to store Fisher test results for diseases
fisher_results <- data.frame(PHENO = labels[which(labels$TYPE == "disease"), "PHENO"], 
                             N_DUP_Dp_subset = NA, N_DUP_Dn_subset = NA, PREVALENCE_DUP_subset = NA, SE_DUP_subset = NA, 
                             N_DUP_Dp_excluded = NA, N_DUP_Dn_excluded = NA, PREVALENCE_DUP_excluded = NA, SE_DUP_excluded = NA,
                             OR_DUP = NA, P_DUP = NA,
                             N_DEL_Dp_subset = NA, N_DEL_Dn_subset = NA, PREVALENCE_DEL_subset = NA, SE_DEL_subset = NA, 
                             N_DEL_Dp_excluded = NA, N_DEL_Dn_excluded = NA, PREVALENCE_DEL_excluded = NA, SE_DEL_excluded = NA,
                             OR_DEL = NA, P_DEL = NA)

# Subset disease dataframe by CNV type
disease_dup_subset <- disease[disease$IID %in% dup_subset, ]
disease_dup_excluded <- disease[disease$IID %in% dup_excluded, ]
disease_del_subset <- disease[disease$IID %in% del_subset, ]
disease_del_excluded <- disease[disease$IID %in% del_excluded, ]

# Loop over diseases to be tested
for (i in 1:nrow(fisher_results)) {
  
  # Define the phenotype
  p <- fisher_results[i, "PHENO"]
  print(paste0("Analyzing: ", p))
  
  # Fill in the table (Duplication)
  if(length(as.numeric(table(disease_dup_subset[, p])[names(table(disease_dup_subset[, p])) == 1])) == 1) {
    fisher_results[i, "N_DUP_Dp_subset"] <- as.numeric(table(disease_dup_subset[, p])[names(table(disease_dup_subset[, p])) == 1])
  } else {fisher_results[i, "N_DUP_Dp_subset"] <- 0}
  
  if(length(as.numeric(table(disease_dup_subset[, p])[names(table(disease_dup_subset[, p])) == 0])) == 1) {
    fisher_results[i, "N_DUP_Dn_subset"] <- as.numeric(table(disease_dup_subset[, p])[names(table(disease_dup_subset[, p])) == 0])
  } else {fisher_results[i, "N_DUP_Dn_subset"] <- 0}
  
  fisher_results[i, "PREVALENCE_DUP_subset"] <- fisher_results[i, "N_DUP_Dp_subset"]/(fisher_results[i, "N_DUP_Dp_subset"] + fisher_results[i, "N_DUP_Dn_subset"])
  fisher_results[i, "SE_DUP_subset"] <- sqrt(fisher_results[i, "PREVALENCE_DUP_subset"] * (1-fisher_results[i, "PREVALENCE_DUP_subset"]) / (fisher_results[i, "N_DUP_Dp_subset"] + fisher_results[i, "N_DUP_Dn_subset"]))
  
  if(length(as.numeric(table(disease_dup_excluded[, p])[names(table(disease_dup_excluded[, p])) == 1])) == 1) {
    fisher_results[i, "N_DUP_Dp_excluded"] <- as.numeric(table(disease_dup_excluded[, p])[names(table(disease_dup_excluded[, p])) == 1])
  } else {fisher_results[i, "N_DUP_Dp_excluded"] <- 0}
  
  if(length(as.numeric(table(disease_dup_excluded[, p])[names(table(disease_dup_excluded[, p])) == 0])) == 1) {
    fisher_results[i, "N_DUP_Dn_excluded"] <- as.numeric(table(disease_dup_excluded[, p])[names(table(disease_dup_excluded[, p])) == 0])
  } else {fisher_results[i, "N_DUP_Dn_excluded"] <- 0}
  
  fisher_results[i, "PREVALENCE_DUP_excluded"] <- fisher_results[i, "N_DUP_Dp_excluded"]/(fisher_results[i, "N_DUP_Dp_excluded"] + fisher_results[i, "N_DUP_Dn_excluded"])
  fisher_results[i, "SE_DUP_excluded"] <- sqrt(fisher_results[i, "PREVALENCE_DUP_excluded"] * (1-fisher_results[i, "PREVALENCE_DUP_excluded"]) / (fisher_results[i, "N_DUP_Dp_excluded"] + fisher_results[i, "N_DUP_Dn_excluded"]))
  fisher_results[i, "OR_DUP"] <- fisher.test(matrix(c(fisher_results[i, "N_DUP_Dp_subset"], fisher_results[i, "N_DUP_Dn_subset"], fisher_results[i, "N_DUP_Dp_excluded"], fisher_results[i, "N_DUP_Dn_excluded"]), nrow = 2), alternative = "two.sided")$estimate
  fisher_results[i, "P_DUP"] <- fisher.test(matrix(c(fisher_results[i, "N_DUP_Dp_subset"], fisher_results[i, "N_DUP_Dn_subset"], fisher_results[i, "N_DUP_Dp_excluded"], fisher_results[i, "N_DUP_Dn_excluded"]), nrow = 2), alternative = "two.sided")$p.value
  
  # Fill in the table (Deletion)
  if(length(as.numeric(table(disease_del_subset[, p])[names(table(disease_del_subset[, p])) == 1])) == 1) {
    fisher_results[i, "N_DEL_Dp_subset"] <- as.numeric(table(disease_del_subset[, p])[names(table(disease_del_subset[, p])) == 1])
  } else {fisher_results[i, "N_DEL_Dp_subset"] <- 0}
  
  if(length(as.numeric(table(disease_del_subset[, p])[names(table(disease_del_subset[, p])) == 0])) == 1) {
    fisher_results[i, "N_DEL_Dn_subset"] <- as.numeric(table(disease_del_subset[, p])[names(table(disease_del_subset[, p])) == 0])
  } else {fisher_results[i, "N_DEL_Dn_subset"] <- 0}
  
  fisher_results[i, "PREVALENCE_DEL_subset"] <- fisher_results[i, "N_DEL_Dp_subset"]/(fisher_results[i, "N_DEL_Dp_subset"] + fisher_results[i, "N_DEL_Dn_subset"])
  fisher_results[i, "SE_DEL_subset"] <- sqrt(fisher_results[i, "PREVALENCE_DEL_subset"] * (1-fisher_results[i, "PREVALENCE_DEL_subset"]) / (fisher_results[i, "N_DEL_Dp_subset"] + fisher_results[i, "N_DEL_Dn_subset"]))
  
  if(length(as.numeric(table(disease_del_excluded[, p])[names(table(disease_del_excluded[, p])) == 1])) == 1) {
    fisher_results[i, "N_DEL_Dp_excluded"] <-as.numeric(table(disease_del_excluded[, p])[names(table(disease_del_excluded[, p])) == 1])
  } else {fisher_results[i, "N_DEL_Dp_excluded"] <- 0}
  
  if(length(as.numeric(table(disease_del_excluded[, p])[names(table(disease_del_excluded[, p])) == 0])) == 1) {
    fisher_results[i, "N_DEL_Dn_excluded"] <- as.numeric(table(disease_del_excluded[, p])[names(table(disease_del_excluded[, p])) == 0])
  } else {fisher_results[i, "N_DEL_Dn_excluded"] <- 0}
  
  fisher_results[i, "PREVALENCE_DEL_excluded"] <- fisher_results[i, "N_DEL_Dp_excluded"]/(fisher_results[i, "N_DEL_Dp_excluded"] + fisher_results[i, "N_DEL_Dn_excluded"])
  fisher_results[i, "SE_DEL_excluded"] <- sqrt(fisher_results[i, "PREVALENCE_DEL_excluded"] * (1-fisher_results[i, "PREVALENCE_DEL_excluded"]) / (fisher_results[i, "N_DEL_Dp_excluded"] + fisher_results[i, "N_DEL_Dn_excluded"]))
  fisher_results[i, "OR_DEL"] <- fisher.test(matrix(c(fisher_results[i, "N_DEL_Dp_excluded"], fisher_results[i, "N_DEL_Dn_excluded"], fisher_results[i, "N_DEL_Dp_excluded"], fisher_results[i, "N_DEL_Dn_excluded"]), nrow = 2), alternative = "two.sided")$estimate
  fisher_results[i, "P_DEL"] <- fisher.test(matrix(c(fisher_results[i, "N_DEL_Dp_excluded"], fisher_results[i, "N_DEL_Dn_excluded"], fisher_results[i, "N_DEL_Dp_excluded"], fisher_results[i, "N_DEL_Dn_excluded"]), nrow = 2), alternative = "two.sided")$p.value
  
}

# Save results
fwrite(fisher_results, "/data/case_control/case_control_fisher_test_SUBSET_vs_EXCLUDED.txt", col.names = T, row.names = F, quote = F, sep = "\t")



########################################################
# STEP 4: Plot
########################################################

# Create a list to store plots
plot_list <- list()

# Color palette
palette <- data.frame(CAT = c("musculoskeletal", "hepatic", "metabolic", "neurologic", "pulmonary", "hematologic", "reproductive", "renal"),
                      color = c(met.brewer("Signac")[12], met.brewer("Signac")[5], met.brewer("Signac")[3], met.brewer("Signac")[11], met.brewer("Signac")[10], met.brewer("Signac")[4], met.brewer("Signac")[2], met.brewer("Signac")[14]))


# Loop over phenotypes
for(i in 1:nrow(labels)) {
  
  ## Define the trait
  p <- labels[i, "PHENO"]
  print(paste0("Analyzing: ", p))
  
  ### Continuous traits ###############################################
  if (labels[i, "TYPE"] == "cont") {
    
    # Create a temporary dataframe & factorize
    df <- rbind(data.frame(PHENO = na.omit(pheno_dup_subset[,p]), GROUP = "DUP_subset"),
                data.frame(PHENO = na.omit(pheno_dup_excluded[,p]), GROUP = "DUP_excluded"),
                data.frame(PHENO = na.omit(pheno_del_subset[,p]), GROUP = "DEL_subset"),
                data.frame(PHENO = na.omit(pheno_del_excluded[,p]), GROUP = "DEL_excluded"))
    df$GROUP <- factor(df$GROUP, levels = c("DEL_excluded", "DEL_subset", "DUP_subset", "DUP_excluded"),
                       labels = c(paste0("DEL\nexcluded\nN = ", length(na.omit(pheno_del_excluded[,p]))),
                                  paste0("DEL\nsubset\nN = ", length(na.omit(pheno_del_subset[,p]))),
                                  paste0("DUP\nsubset\nN = ", length(na.omit(pheno_dup_subset[,p]))),
                                  paste0("DUP\nexcluded\nN = ", length(na.omit(pheno_dup_excluded[,p])))))
    
    # Add header
    df$HEADER <- factor(labels[i, "TITLE"])
    
    # Calculate plot limits
    y_lim_range <- range(c(boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[1]])$stats[c(1,5)],
                           boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[2]])$stats[c(1,5)],
                           boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[3]])$stats[c(1,5)],
                           boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[4]])$stats[c(1,5)]))
    
    # Define significance
    sig_df_del <- data.frame(start = factor(levels(df$GROUP)[1]), end = factor(levels(df$GROUP)[2]), y = y_lim_range[2] + 0.2 * diff(y_lim_range) / 2)
    if(t_test_results[t_test_results$PHENO == p, "P_DEL"] < 0.05) {
      sig_df_del$label <- paste0("p = ", pvalString(t_test_results[t_test_results$PHENO == p, "P_DEL"], format = "exact", digits = 2))
    } else { 
      sig_df_del$label <- "ns"
    }
    
    sig_df_dup <- data.frame(start = factor(levels(df$GROUP)[3]), end = factor(levels(df$GROUP)[4]), y = y_lim_range[2] + 0.2 * diff(y_lim_range) / 2)
    if(t_test_results[t_test_results$PHENO == p, "P_DUP"] < 0.05) {
      sig_df_dup$label <- paste0("p = ", pvalString(t_test_results[t_test_results$PHENO == p, "P_DUP"], format = "exact", digits = 2))
    } else {
      sig_df_dup$label <- "ns"
    }
    sig_df <- rbind(sig_df_del, sig_df_dup); rm(sig_df_del, sig_df_dup)
    
    # Plot
    plot_list[[i]] <- ggplot(df) +
                        # Facet
                        facet_wrap(.~ HEADER) +
                        # Boxplot
                        geom_boxplot(aes(x = GROUP, y = PHENO, fill = GROUP, alpha = GROUP), outlier.shape = NA, fill = palette[which(palette$CAT == labels[i, "CAT"]), "color"]) + 
                        geom_jitter(data = df,
                                    aes(x = GROUP, y = PHENO, fill = GROUP, alpha = GROUP),
                                    width = 0.3, height = 0, alpha = 0.2, show.legend = F) +
                        scale_alpha_manual(values = c(0.3, 1, 1, 0.3), guide = "none") +
                        # P-value
                        geom_signif(data = sig_df, aes(xmin = start, xmax = end, annotations = label, y_position = y), textsize = 3.5, vjust = -0.4, manual = TRUE, tip_length = 0) +
                        # Layout
                        xlab("") + ylab(ifelse(p == "BMD", expression("BMD [g/cm"^2*"]"), 
                                               ifelse(p == "platelet_count", expression("platelet count [10"^9*" cells/L]"),
                                                      ifelse(p == "Cr", expression("creatinine ["*mu*"mol/L]"), labels[i, "Y_AXIS"])))) +
                        coord_cartesian(ylim = y_lim_range + c(-0.15, 0.5) * diff(y_lim_range) / 2) +
                        theme_bw() +
                        theme(text = element_text(family = "Arial"),
                              axis.text = element_text(size = 9),
                              axis.title.y = element_text(size = 11, margin = margin(t = 0, r = 5, b = 0, l = 0)),
                              strip.text = element_text(size = 12.5, face = "bold", color = "#2B4050"),
                              strip.background = element_rect(fill = "#F4F4F4", color = "#2B4050"))
  }
  
  
  ### Diseases ##################################################
  if (labels[i, "TYPE"] == "disease") {
    
    # Create a temporary dataframe & factorize
    df <- data.frame(GROUP = c(paste0("DEL\nexcluded\n", fisher_results[fisher_results$PHENO == p, "N_DEL_Dp_excluded"], "/", fisher_results[fisher_results$PHENO == p, "N_DEL_Dp_excluded"] + fisher_results[fisher_results$PHENO == p, "N_DEL_Dn_excluded"]), 
                               paste0("DEL\nsubset\n", fisher_results[fisher_results$PHENO == p, "N_DEL_Dp_subset"], "/", fisher_results[fisher_results$PHENO == p, "N_DEL_Dp_subset"] + fisher_results[fisher_results$PHENO == p, "N_DEL_Dn_subset"]), 
                               paste0("DUP\nsubset\n", fisher_results[fisher_results$PHENO == p, "N_DUP_Dp_subset"], "/", fisher_results[fisher_results$PHENO == p, "N_DUP_Dp_subset"] + fisher_results[fisher_results$PHENO == p, "N_DUP_Dn_subset"]), 
                               paste0("DUP\nexcluded\n", fisher_results[fisher_results$PHENO == p, "N_DUP_Dp_excluded"], "/", fisher_results[fisher_results$PHENO == p, "N_DUP_Dp_excluded"] + fisher_results[fisher_results$PHENO == p, "N_DUP_Dn_excluded"])),
                     percentage = c(100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DEL_excluded"],
                                    100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DEL_subset"],
                                    100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DUP_subset"],
                                    100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DUP_excluded"]),
                     SE = c(100*fisher_results[fisher_results$PHENO == p, "SE_DEL_excluded"],
                            100*fisher_results[fisher_results$PHENO == p, "SE_DEL_subset"],
                            100*fisher_results[fisher_results$PHENO == p, "SE_DUP_subset"],
                            100*fisher_results[fisher_results$PHENO == p, "SE_DUP_excluded"]))
    df$GROUP <- factor(df$GROUP, levels =  df$GROUP)
    
    # Add header
    df$HEADER <- factor(labels[i, "TITLE"])
    
    # Annotation position
    annotation_step <- max(df$percentage + df$SE)*0.1
    df$y <- df$percentage + df$SE + annotation_step
    df$LABEL <- paste0(round(df$percentage, 1), "%")
    
    # Calculate plotlimits
    y_lim <- max(df$y) + 3.2*annotation_step
    
    # Define significance
    sig_df_del <- data.frame(start = factor(levels(df$GROUP)[1]), end = factor(levels(df$GROUP)[2]), y = max(df$y) + 1.8*annotation_step)
    if(fisher_results[fisher_results$PHENO == p, "P_DEL"] < 0.05) {
      sig_df_del$label <- paste0("p = ", pvalString(fisher_results[fisher_results$PHENO == p, "P_DEL"], format = "exact", digits = 2))
    } else { 
      sig_df_del$label <- "ns"
    }
    
    sig_df_dup <- data.frame(start = factor(levels(df$GROUP)[3]), end = factor(levels(df$GROUP)[4]), y = max(df$y) + 1.8*annotation_step)
    if(fisher_results[fisher_results$PHENO == p, "P_DUP"] < 0.05) {
      sig_df_dup$label <- paste0("p = ", pvalString(fisher_results[fisher_results$PHENO == p, "P_DUP"], format = "exact", digits = 2))
    } else {
      sig_df_dup$label <- "ns"
    }
    sig_df <- rbind(sig_df_del, sig_df_dup); rm(sig_df_del, sig_df_dup)
    
    # Plot
    plot_list[[i]] <- ggplot(df) +
                        # Facet
                        facet_wrap(.~ HEADER) +
                        # Bars
                        geom_bar(aes(x = GROUP, y = percentage, alpha = GROUP), stat = "identity", color = "black", fill = palette[which(palette$CAT == labels[i, "CAT"]), "color"]) + 
                        scale_alpha_manual(values = c(0.3, 1, 1, 0.3), guide = "none") +
                        # Error bars
                        geom_errorbar(aes(x = GROUP, y = percentage, ymin = percentage-SE, ymax =  percentage+SE), width = 0.15) +
                        # Annotation
                        geom_text(mapping = aes(x = GROUP, y = y, label = LABEL), position = position_stack(vjust = 1), size = 3.7) +
                        # p-values
                        geom_signif(data = sig_df, aes(xmin = start, xmax = end, annotations = label, y_position = y), textsize = 3.5, vjust = -0.4, manual = TRUE, tip_length = 0) +
                        # Layout
                        xlab("") + ylab(labels[i, "Y_AXIS"]) +
                        coord_cartesian(ylim = c(0, y_lim)) +
                        theme_bw() +
                        theme(text = element_text(family = "Arial"),
                              axis.text = element_text(size = 9),
                              axis.title.y = element_text(size = 11, margin = margin(t = 0, r = 5, b = 0, l = 0)),
                              strip.text = element_text(size = 12.5, face = "bold", color = "#2B4050"),
                              strip.background = element_rect(fill = "#F4F4F4", color = "#2B4050"))
  }
}

# Assemble plots & save
pdf("/plot/matched_controls_ExcludedSubset.pdf", width = 12, height = 15)
showtext_auto() 
do.call("grid.arrange", c(plot_list, ncol=4))
dev.off()
showtext_auto(FALSE)