########################################################
# Libraries
########################################################
library(dplyr)
library(data.table)
library(MetBrewer)
library(ggplot2)
library(gridExtra)
library(pixiedust)
library(ggsignif)
library(showtext)
font_add("Arial", "/System/Library/Fonts/Supplemental/Arial.ttf", bold = "/System/Library/Fonts/Supplemental/Arial Bold.ttf", italic = "/System/Library/Fonts/Supplemental/Arial Italic.ttf", bolditalic = "/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf")



########################################################
# STEP 1: Load data
########################################################

# Load CNV carriers and subset those with at least 25 matched controls (files generated by script/04_matched_control/01_select_matched_controls.R)
dup <- as.data.frame(fread("/data/case_control/controls_dup_min_25_count.txt")) 
dup <- dup[which(dup$count >= 25), "IID"]
del <- as.data.frame(fread("/data/case_control/controls_del_min_25_count.txt")) 
del <- del[which(del$count >= 25), "IID"]

# Load CNV matched controls controls (files generated by script/04_matched_control/01_select_matched_controls.R)
dup_ctrl <- as.data.frame(fread("/data/case_control/controls_dup_min_25.txt.gz", select = c(1)))$IID
del_ctrl <- as.data.frame(fread("/data/case_control/controls_del_min_25.txt.gz", select = c(1)))$IID

# Load continuous phenotype data (non-transformed; as described in Auwerx et al., 2022 (AJHG); identifier + 1 column/trait); 
# Sex-specific traits originate from sex-specific data files and are appended to the main dataframe
pheno_All <- as.data.frame(fread("pheno_continuous_WB_raw_All.txt.gz"))
pheno_M <- as.data.frame(fread("pheno_continuous_WB_raw_M.txt.gz"))
pheno_F <- as.data.frame(fread("pheno_continuous_WB_raw_F.txt.gz"))
pheno <- left_join(pheno_All, pheno_M[, names(pheno_M) %in% c("IID", "balding", "facial_hair")], by = "IID"); rm(pheno_All, pheno_M)
pheno <- left_join(pheno, pheno_F[, names(pheno_F) %in% c("IID", "menarche", "menopause", "birth_weight_first_child")], by = "IID"); rm(pheno_F)

# Load disease status data (identifier + 1 column/trait); 
# Sex-specific diseases originate from sex-specific data files and are appended to the main dataframe; 
# Data file is encoded so that cases are 1, controls are 0, and missing data NA
disease <- as.data.frame(fread("pheno_ICD10_All.txt.gz"))
disease[disease == 1] <- 0
disease[disease == 2] <- 1

# Load labels; This list contain the 23 traits that associate with the CNVs but are lost after adjustment for BMI or EA or are too correlated to the latter
# File created manually, which contains the following columns for each of the tested traits:
# PHENO: short phenotype name matching other dataframes;
# TITLE: plot title;
# Y-AXIS: label for the plot's y-axis;
# CAT: phenotype category (for color);
# TYPE: either "cont" or "disease", will determine which plot type is needed.
labels <- as.data.frame(fread("case_control_trait_labels_NegCtrl.txt"))



########################################################
# STEP 2: Loop over phenotypes
########################################################

### Continuous traits ##################################

# Create an empty dataframe to store t-test results for continuous traits
t_test_results <- data.frame(PHENO = labels[which(labels$TYPE == "cont"), "PHENO"], 
                             N_DUP = NA, MEAN_DUP = NA, SE_DUP = NA, N_DUP_CTRL = NA, MEAN_DUP_CTRL = NA, SE_DUP_CTRL = NA, P_DUP = NA,
                             N_DEL = NA, MEAN_DEL = NA, SE_DEL = NA, N_DEL_CTRL = NA, MEAN_DEL_CTRL = NA, SE_DEL_CTRL = NA, P_DEL = NA)

# Subset continuous phenotype dataframe by CNV type
pheno_dup <- pheno[pheno$IID %in% dup, ]
pheno_dup_ctrl <- pheno[pheno$IID %in% dup_ctrl, ]
pheno_del <- pheno[pheno$IID %in% del, ]
pheno_del_ctrl <- pheno[pheno$IID %in% del_ctrl, ]

# Loop over phenotypes to be tested
for (i in 1:nrow(t_test_results)) {
  
  # Define the phenotype
  p <- t_test_results[i, "PHENO"]
  print(paste0("Analyzing: ", p))
  
  # Fill in the table (Duplication)
  t_test_results[i, "N_DUP"] <- length(na.omit(pheno_dup[, p]))
  t_test_results[i, "MEAN_DUP"] <- mean(na.omit(pheno_dup[, p]))
  t_test_results[i, "SE_DUP"] <- sd(na.omit(pheno_dup[, p]))/sqrt(length(na.omit(pheno_dup[, p])))
  t_test_results[i, "N_DUP_CTRL"] <- length(na.omit(pheno_dup_ctrl[, p]))
  t_test_results[i, "MEAN_DUP_CTRL"] <- mean(na.omit(pheno_dup_ctrl[, p]))
  t_test_results[i, "SE_DUP_CTRL"] <- sd(na.omit(pheno_dup_ctrl[, p]))/sqrt(length(na.omit(pheno_dup_ctrl[, p])))
  t_test_results[i, "P_DUP"] <- t.test(na.omit(pheno_dup[, p]), na.omit(pheno_dup_ctrl[, p]), alternative = "two.sided")$p.value
  
  # Fill in teh table (Deletion)
  t_test_results[i, "N_DEL"] <- length(na.omit(pheno_del[, p]))
  t_test_results[i, "MEAN_DEL"] <- mean(na.omit(pheno_del[, p]))
  t_test_results[i, "SE_DEL"] <- sd(na.omit(pheno_del[, p]))/sqrt(length(na.omit(pheno_del[, p])))
  t_test_results[i, "N_DEL_CTRL"] <- length(na.omit(pheno_del_ctrl[,p ]))
  t_test_results[i, "MEAN_DEL_CTRL"] <- mean(na.omit(pheno_del_ctrl[, p]))
  t_test_results[i, "SE_DEL_CTRL"] <- sd(na.omit(pheno_del_ctrl[, p]))/sqrt(length(na.omit(pheno_del_ctrl[, p])))
  t_test_results[i, "P_DEL"] <- t.test(na.omit(pheno_del[, p]), na.omit(pheno_del_ctrl[, p]), alternative = "two.sided")$p.value
  
}

# Save results
fwrite(t_test_results, "/data/case_control/case_control_NEG_t_test.txt", col.names = T, row.names = F, quote = F, sep = "\t")


### Diseases #####################################

# Create an empty dataframe to store Fisher test results for diseases
fisher_results <- data.frame(PHENO = labels[which(labels$TYPE == "disease"), "PHENO"], 
                             N_DUP_Dp = NA, N_DUP_Dn = NA, PREVALENCE_DUP = NA, SE_DUP = NA, 
                             N_DUP_CTRL_Dp = NA, N_DUP_CTRL_Dn = NA, PREVALENCE_DUP_CTRL = NA, SE_DUP_CTRL = NA,
                             OR_DUP = NA, P_DUP = NA,
                             N_DEL_Dp = NA, N_DEL_Dn = NA, PREVALENCE_DEL = NA, SE_DEL = NA, 
                             N_DEL_CTRL_Dp = NA, N_DEL_CTRL_Dn = NA, PREVALENCE_DEL_CTRL = NA, SE_DEL_CTRL = NA,
                             OR_DEL = NA, P_DEL = NA)

# Subset disease dataframe by CNV type
disease_dup <- disease[disease$IID %in% dup, ]
disease_dup_ctrl <- disease[disease$IID %in% dup_ctrl, ]
disease_del <- disease[disease$IID %in% del, ]
disease_del_ctrl <- disease[disease$IID %in% del_ctrl, ]

# Loop over diseases to be tested
for (i in 1:nrow(fisher_results)) {
  
  # Define the disease
  p <- fisher_results[i, "PHENO"]
  print(paste0("Analyzing: ", p))
  
  # Fill in the table (Duplication)
  if(length(as.numeric(table(disease_dup[, p])[names(table(disease_dup[, p])) == 1])) == 1) {
    fisher_results[i, "N_DUP_Dp"] <- as.numeric(table(disease_dup[, p])[names(table(disease_dup[, p])) == 1])
  } else {fisher_results[i, "N_DUP_Dp"] <- 0}
  
  if(length(as.numeric(table(disease_dup[, p])[names(table(disease_dup[, p])) == 0])) == 1) {
    fisher_results[i, "N_DUP_Dn"] <- as.numeric(table(disease_dup[, p])[names(table(disease_dup[, p])) == 0])
  } else {fisher_results[i, "N_DUP_Dn"] <- 0}
  
  fisher_results[i, "PREVALENCE_DUP"] <- fisher_results[i, "N_DUP_Dp"]/(fisher_results[i, "N_DUP_Dp"] + fisher_results[i, "N_DUP_Dn"])
  fisher_results[i, "SE_DUP"] <- sqrt(fisher_results[i, "PREVALENCE_DUP"] * (1-fisher_results[i, "PREVALENCE_DUP"]) / (fisher_results[i, "N_DUP_Dp"] + fisher_results[i, "N_DUP_Dn"]))
  
  if(length(as.numeric(table(disease_dup_ctrl[, p])[names(table(disease_dup_ctrl[, p])) == 1])) == 1) {
    fisher_results[i, "N_DUP_CTRL_Dp"] <- as.numeric(table(disease_dup_ctrl[, p])[names(table(disease_dup_ctrl[, p])) == 1])
  } else {fisher_results[i, "N_DUP_CTRL_Dp"] <- 0}
  
  if(length(as.numeric(table(disease_dup_ctrl[, p])[names(table(disease_dup_ctrl[, p])) == 0])) == 1) {
    fisher_results[i, "N_DUP_CTRL_Dn"] <- as.numeric(table(disease_dup_ctrl[, p])[names(table(disease_dup_ctrl[, p])) == 0])
  } else {fisher_results[i, "N_DUP_CTRL_Dn"] <- 0}
  
  fisher_results[i, "PREVALENCE_DUP_CTRL"] <- fisher_results[i, "N_DUP_CTRL_Dp"]/(fisher_results[i, "N_DUP_CTRL_Dp"] + fisher_results[i, "N_DUP_CTRL_Dn"])
  fisher_results[i, "SE_DUP_CTRL"] <- sqrt(fisher_results[i, "PREVALENCE_DUP_CTRL"] * (1-fisher_results[i, "PREVALENCE_DUP_CTRL"]) / (fisher_results[i, "N_DUP_CTRL_Dp"] + fisher_results[i, "N_DUP_CTRL_Dn"]))
  fisher_results[i, "OR_DUP"] <- fisher.test(matrix(c(fisher_results[i, "N_DUP_Dp"], fisher_results[i, "N_DUP_Dn"], fisher_results[i, "N_DUP_CTRL_Dp"], fisher_results[i, "N_DUP_CTRL_Dn"]), nrow = 2), alternative = "two.sided")$estimate
  fisher_results[i, "P_DUP"] <- fisher.test(matrix(c(fisher_results[i, "N_DUP_Dp"], fisher_results[i, "N_DUP_Dn"], fisher_results[i, "N_DUP_CTRL_Dp"], fisher_results[i, "N_DUP_CTRL_Dn"]), nrow = 2), alternative = "two.sided")$p.value

  # Fill in the table (Deletion)
  if(length(as.numeric(table(disease_del[, p])[names(table(disease_del[, p])) == 1])) == 1) {
    fisher_results[i, "N_DEL_Dp"] <- as.numeric(table(disease_del[, p])[names(table(disease_del[, p])) == 1])
  } else {fisher_results[i, "N_DEL_Dp"] <- 0}
  
  if(length(as.numeric(table(disease_del[, p])[names(table(disease_del[, p])) == 0])) == 1) {
    fisher_results[i, "N_DEL_Dn"] <- as.numeric(table(disease_del[, p])[names(table(disease_del[, p])) == 0])
  } else {fisher_results[i, "N_DEL_Dn"] <- 0}
  
  fisher_results[i, "PREVALENCE_DEL"] <- fisher_results[i, "N_DEL_Dp"]/(fisher_results[i, "N_DEL_Dp"] + fisher_results[i, "N_DEL_Dn"])
  fisher_results[i, "SE_DEL"] <- sqrt(fisher_results[i, "PREVALENCE_DEL"] * (1-fisher_results[i, "PREVALENCE_DEL"]) / (fisher_results[i, "N_DEL_Dp"] + fisher_results[i, "N_DEL_Dn"]))
  
  if(length(as.numeric(table(disease_del_ctrl[, p])[names(table(disease_del_ctrl[, p])) == 1])) == 1) {
    fisher_results[i, "N_DEL_CTRL_Dp"] <-as.numeric(table(disease_del_ctrl[, p])[names(table(disease_del_ctrl[, p])) == 1])
  } else {fisher_results[i, "N_DEL_CTRL_Dp"] <- 0}
  
  if(length(as.numeric(table(disease_del_ctrl[, p])[names(table(disease_del_ctrl[, p])) == 0])) == 1) {
    fisher_results[i, "N_DEL_CTRL_Dn"] <- as.numeric(table(disease_del_ctrl[, p])[names(table(disease_del_ctrl[, p])) == 0])
  } else {fisher_results[i, "N_DEL_CTRL_Dn"] <- 0}
  
  fisher_results[i, "PREVALENCE_DEL_CTRL"] <- fisher_results[i, "N_DEL_CTRL_Dp"]/(fisher_results[i, "N_DEL_CTRL_Dp"] + fisher_results[i, "N_DEL_CTRL_Dn"])
  fisher_results[i, "SE_DEL_CTRL"] <- sqrt(fisher_results[i, "PREVALENCE_DEL_CTRL"] * (1-fisher_results[i, "PREVALENCE_DEL_CTRL"]) / (fisher_results[i, "N_DEL_CTRL_Dp"] + fisher_results[i, "N_DEL_CTRL_Dn"]))
  fisher_results[i, "OR_DEL"] <- fisher.test(matrix(c(fisher_results[i, "N_DEL_Dp"], fisher_results[i, "N_DEL_Dn"], fisher_results[i, "N_DEL_CTRL_Dp"], fisher_results[i, "N_DEL_CTRL_Dn"]), nrow = 2), alternative = "two.sided")$estimate
  fisher_results[i, "P_DEL"] <- fisher.test(matrix(c(fisher_results[i, "N_DEL_Dp"], fisher_results[i, "N_DEL_Dn"], fisher_results[i, "N_DEL_CTRL_Dp"], fisher_results[i, "N_DEL_CTRL_Dn"]), nrow = 2), alternative = "two.sided")$p.value
  
}

# Save results
fwrite(fisher_results, "/data/case_control/case_control_NegCtrl_fisher_test.txt", col.names = T, row.names = F, quote = F, sep = "\t")



########################################################
# STEP 3: Plot
########################################################

# Create a list to store plots
plot_list <- list()

# Define the color palette
palette <- data.frame(CAT = c("musculoskeletal", "hepatic", "metabolic", "neurologic", "pulmonary", "hematologic", "reproductive", "renal", "cardiovascular"),
                      color = c(met.brewer("Signac")[12], met.brewer("Signac")[5], met.brewer("Signac")[3], met.brewer("Signac")[11], met.brewer("Signac")[10], met.brewer("Signac")[4], met.brewer("Signac")[2], met.brewer("Signac")[14], met.brewer("Signac")[8]))

# Loop over phenotypes
for(i in 1:nrow(labels)) {
  
  ## Define the phenotype
  p <- labels[i, "PHENO"]
  print(paste0("Analyzing: ", p))
  
  ### Continuous traits ###############################################
  if (labels[i, "TYPE"] == "cont") {
    
    # Create a temporary dataframe & factorize
    df <- rbind(data.frame(PHENO = na.omit(pheno_dup[,p]), GROUP = "DUP"),
                data.frame(PHENO = na.omit(pheno_dup_ctrl[,p]), GROUP = "DUP_CTRL"),
                data.frame(PHENO = na.omit(pheno_del[,p]), GROUP = "DEL"),
                data.frame(PHENO = na.omit(pheno_del_ctrl[,p]), GROUP = "DEL_CTRL"))
    df$GROUP <- factor(df$GROUP, levels = c("DEL", "DEL_CTRL", "DUP_CTRL", "DUP"),
                       labels = c(paste0("DEL\nN = ", length(na.omit(pheno_del[,p]))),
                                  paste0("DEL ctrl\nN = ", length(na.omit(pheno_del_ctrl[,p]))),
                                  paste0("DUP ctrl\nN = ", length(na.omit(pheno_dup_ctrl[,p]))),
                                  paste0("DUP\nN = ", length(na.omit(pheno_dup[,p])))))
    
    # Add header
    df$HEADER <- factor(labels[i, "TITLE"])
    
    # Calculate plot limits
    y_lim_range <- range(c(boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[1]])$stats[c(1,5)],
                           boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[2]])$stats[c(1,5)],
                           boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[3]])$stats[c(1,5)],
                           boxplot.stats(df$PHENO[df$GROUP %in% levels(df$GROUP)[4]])$stats[c(1,5)]))

    # Define significance
    sig_df_del <- data.frame(start = factor(levels(df$GROUP)[1]), end = factor(levels(df$GROUP)[2]), y = y_lim_range[2] + 0.2 * diff(y_lim_range) / 2)
    if(t_test_results[t_test_results$PHENO == p, "P_DEL"] < 0.05) {
      sig_df_del$label <- paste0("p = ", pvalString(t_test_results[t_test_results$PHENO == p, "P_DEL"], format = "exact", digits = 2))
    } else { 
      sig_df_del$label <- "ns"
    }
      
    sig_df_dup <- data.frame(start = factor(levels(df$GROUP)[3]), end = factor(levels(df$GROUP)[4]), y = y_lim_range[2] + 0.2 * diff(y_lim_range) / 2)
    if(t_test_results[t_test_results$PHENO == p, "P_DUP"] < 0.05) {
      sig_df_dup$label <- paste0("p = ", pvalString(t_test_results[t_test_results$PHENO == p, "P_DUP"], format = "exact", digits = 2))
    } else {
      sig_df_dup$label <- "ns"
    }
    sig_df <- rbind(sig_df_del, sig_df_dup); rm(sig_df_del, sig_df_dup)
    
    # Plot
    plot_list[[i]] <- ggplot(df) +
                      # Facet
                      facet_wrap(.~ HEADER) +
                      # Boxplot
                      geom_boxplot(aes(x = GROUP, y = PHENO, fill = GROUP, alpha = GROUP), outlier.shape = NA, fill = palette[which(palette$CAT == labels[i, "CAT"]), "color"]) + 
                      geom_jitter(data = df[df$GROUP %in% levels(df$GROUP)[c(1,4)], ], 
                                  aes(x = GROUP, y = PHENO, fill = GROUP, alpha = GROUP),
                                  width = 0.3, height = 0, alpha = 0.2, show.legend = F) +
                      scale_alpha_manual(values = c(1, 0.3, 0.3, 1), guide = "none") +
                      # P-value
                      geom_signif(data = sig_df, aes(xmin = start, xmax = end, annotations = label, y_position = y), textsize = 3.5, vjust = -0.4, manual = TRUE, tip_length = 0) +
                      # Layout
                      xlab("") + ylab(ifelse(p == "BMI", expression("BMI [kg/m"^2*"]"), 
                                            ifelse(p == "neutrophil_count", expression("neutrophil count [10"^9*" cells/L]"),
                                                   ifelse(p == "urate", expression("urate ["*mu*"mol/L]"), labels[i, "Y_AXIS"])))) +
                      coord_cartesian(ylim = y_lim_range + c(-0.15, 0.5) * diff(y_lim_range) / 2) +
                      theme_bw() +
                      theme(text = element_text(family = "Arial"),
                            axis.text = element_text(size = 9),
                            axis.title.y = element_text(size = 11, margin = margin(t = 0, r = 5, b = 0, l = 0)),
                            strip.text = element_text(size = 12.5, face = "bold", color = "#2B4050"),
                            strip.background = element_rect(fill = "#F4F4F4", color = "#2B4050"))
  }
  
  
  ### Diseases ######################################################
  if (labels[i, "TYPE"] == "disease") {
    
    # Create a temporary dataframe & factorize
    df <- data.frame(GROUP = c(paste0("DEL\n", fisher_results[fisher_results$PHENO == p, "N_DEL_Dp"], "/", fisher_results[fisher_results$PHENO == p, "N_DEL_Dp"] + fisher_results[fisher_results$PHENO == p, "N_DEL_Dn"]), 
                               paste0("DEL ctrl\n", fisher_results[fisher_results$PHENO == p, "N_DEL_CTRL_Dp"], "/", fisher_results[fisher_results$PHENO == p, "N_DEL_CTRL_Dp"] + fisher_results[fisher_results$PHENO == p, "N_DEL_CTRL_Dn"]), 
                               paste0("DUP ctrl\n", fisher_results[fisher_results$PHENO == p, "N_DUP_CTRL_Dp"], "/", fisher_results[fisher_results$PHENO == p, "N_DUP_CTRL_Dp"] + fisher_results[fisher_results$PHENO == p, "N_DUP_CTRL_Dn"]), 
                               paste0("DUP\n", fisher_results[fisher_results$PHENO == p, "N_DUP_Dp"], "/", fisher_results[fisher_results$PHENO == p, "N_DUP_Dp"] + fisher_results[fisher_results$PHENO == p, "N_DUP_Dn"])),
                     percentage = c(100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DEL"],
                                    100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DEL_CTRL"],
                                    100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DUP_CTRL"],
                                    100*fisher_results[fisher_results$PHENO == p, "PREVALENCE_DUP"]),
                     SE = c(100*fisher_results[fisher_results$PHENO == p, "SE_DEL"],
                            100*fisher_results[fisher_results$PHENO == p, "SE_DEL_CTRL"],
                            100*fisher_results[fisher_results$PHENO == p, "SE_DUP_CTRL"],
                            100*fisher_results[fisher_results$PHENO == p, "SE_DUP"]))
    df$GROUP <- factor(df$GROUP, levels =  df$GROUP)
    
    # Add header
    df$HEADER <- factor(labels[i, "TITLE"])
    
    # Annotation position
    annotation_step <- max(df$percentage + df$SE)*0.1
    df$y <- df$percentage + df$SE + annotation_step
    df$LABEL <- paste0(round(df$percentage, 1), "%")
    
    # Calculate plot limits
    y_lim <- max(df$y) + 3.2*annotation_step
    
    # Define significance
    sig_df_del <- data.frame(start = factor(levels(df$GROUP)[1]), end = factor(levels(df$GROUP)[2]), y = max(df$y) + 1.8*annotation_step)
    if(fisher_results[fisher_results$PHENO == p, "P_DEL"] < 0.05) {
      sig_df_del$label <- paste0("p = ", pvalString(fisher_results[fisher_results$PHENO == p, "P_DEL"], format = "exact", digits = 2))
    } else { 
      sig_df_del$label <- "ns"
    }
    
    sig_df_dup <- data.frame(start = factor(levels(df$GROUP)[3]), end = factor(levels(df$GROUP)[4]), y = max(df$y) + 1.8*annotation_step)
    if(fisher_results[fisher_results$PHENO == p, "P_DUP"] < 0.05) {
      sig_df_dup$label <- paste0("p = ", pvalString(fisher_results[fisher_results$PHENO == p, "P_DUP"], format = "exact", digits = 2))
    } else {
      sig_df_dup$label <- "ns"
    }
    sig_df <- rbind(sig_df_del, sig_df_dup); rm(sig_df_del, sig_df_dup)
    
    # Plot
    plot_list[[i]] <- ggplot(df) +
                      # Facet
                      facet_wrap(.~ HEADER) +
                      # Bars
                      geom_bar(aes(x = GROUP, y = percentage, alpha = GROUP), stat = "identity", color = "black", fill = palette[which(palette$CAT == labels[i, "CAT"]), "color"]) + 
                      scale_alpha_manual(values = c(1, 0.3, 0.3, 1), guide = "none") +
                      # Error bars
                      geom_errorbar(aes(x = GROUP, y = percentage, ymin = percentage-SE, ymax =  percentage+SE), width = 0.15) +
                      # Annotation
                      geom_text(mapping = aes(x = GROUP, y = y, label = LABEL), position = position_stack(vjust = 1), size = 3.7) +
                      # p-values
                      geom_signif(data = sig_df, aes(xmin = start, xmax = end, annotations = label, y_position = y), textsize = 3.5, vjust = -0.4, manual = TRUE, tip_length = 0) +
                      # Layout
                      xlab("") + ylab(labels[i, "Y_AXIS"]) +
                      coord_cartesian(ylim = c(0, y_lim)) +
                      theme_bw() +
                      theme(text = element_text(family = "Arial"),
                            axis.text = element_text(size = 9),
                            axis.title.y = element_text(size = 11, margin = margin(t = 0, r = 5, b = 0, l = 0)),
                            strip.text = element_text(size = 12.5, face = "bold", color = "#2B4050"),
                            strip.background = element_rect(fill = "#F4F4F4", color = "#2B4050"))
    
  }

}

# Assemble plots & save
pdf("/plot/matched_controls_NegCtrl.pdf", width = 12, height = 15)
showtext_auto() 
do.call("grid.arrange", c(plot_list, ncol=4))
dev.off()
showtext_auto(FALSE)