########################################################
# Libraries
########################################################
library(dplyr)
library(data.table)
library(MetBrewer)
library(ggplot2)
library(ggforestplot)
library(showtext)
font_add("Arial", "/System/Library/Fonts/Supplemental/Arial.ttf", bold = "/System/Library/Fonts/Supplemental/Arial Bold.ttf", italic = "/System/Library/Fonts/Supplemental/Arial Italic.ttf", bolditalic = "/System/Library/Fonts/Supplemental/Arial Bold Italic.ttf")



########################################################
# STEP 1: Load data
########################################################

# Load summary data with correction (generated by script/02_covariate_correction/03_summary_covariate_correction.R)
df <- as.data.frame(fread("/data/summary_correction.txt"))



########################################################
# STEP 2: Define relevant pairs
########################################################

# Select relevant trait-mediator pairs for testing through MR, i.e., gained or lost significance upon covariate adjustment
sig_lost <- df[which(df$P <= 0.05/117 & df$P_C > 0.05/117), c("PHENO", "MEDIATOR")]
sig_gain <- df[which(df$P > 0.05/117 & df$P_C <= 0.05/117), c("PHENO", "MEDIATOR")]
df <- rbind(sig_lost, sig_gain)
rm(sig_lost, sig_gain)

# Map to MR names (header: MR_name; PHENO; LABEL);
# MR_name: phenotypes names as used by the MR pipeline; 
# PHENO: short names used by other analyses, inc. in "summary_correction.txt";
# LABEL: is a full-length phenotype description
mr_mapping <- as.data.frame(fread("MR_trait_mapping_PHENO.txt", fill = T))

# Loop over retained pairs
for(i in 1:nrow(df)) {
  
  # Define the mediator-trait pair
  p <- df[i, "PHENO"]
  m <- df[i, "MEDIATOR"]
  if(m %in% c("BMI", "height", "TDI")) {m <- paste0(m, "_PanUKBB")}
  
  # Map the phenotype
  df[i, "PHENO_MR"] <- mr_mapping[which(mr_mapping$PHENO == p), "MR_name"]
  
  # Map the mediator
  df[i, "MEDIATOR_MR"] <- mr_mapping[which(mr_mapping$PHENO == m), "MR_name"]
  
}

# Save
fwrite(df, "/data/MR/pairs_bidirectional_MR.txt", col.names = T, row.names = F, quote = F, sep = "\t")



########################################################
# STEP 3: Load & extract MR data
########################################################

# Load MR data (generated by script/03_Mendelian_randomization/01_MR_pipeline) & subset IVW results
mr <- as.data.frame(fread("/data/MR/MR_merged_results.tsv"))
mr <- mr[which(mr$method == "Inverse variance weighted"), ]

# Extract MR data for relevant mediator-trait pairs
for (i in 1:nrow(df)) {
  
  # Define the mediator-trait pair
  p <- df[i, "PHENO_MR"]
  m <- df[i, "MEDIATOR_MR"]
  print(paste0("Analyzing the relation between ", df[i, "MEDIATOR"], " and ", df[i, "PHENO"]))
  
  # Fill in the table
  df[i, "Niv_forward"] <- mr[which(mr$exposure == m & mr$outcome == p), "nsnp"]
  df[i, "ALPHA_forward"] <- mr[which(mr$exposure == m & mr$outcome == p), "b"]
  df[i, "SE_forward"] <- mr[which(mr$exposure == m & mr$outcome == p), "se"]
  df[i, "P_forward"] <- mr[which(mr$exposure == m & mr$outcome == p), "pval"]
  
  df[i, "Niv_reverse"] <- mr[which(mr$exposure == p & mr$outcome == m), "nsnp"]
  df[i, "ALPHA_reverse"] <- mr[which(mr$exposure == p & mr$outcome == m), "b"]
  df[i, "SE_reverse"] <- mr[which(mr$exposure == p & mr$outcome == m), "se"]
  df[i, "P_reverse"] <- mr[which(mr$exposure == p & mr$outcome == m), "pval"]
  
}



########################################################
# STEP 3: Factorize & remodel
########################################################

# Factorize mediator corrections
df$MEDIATOR <- factor(df$MEDIATOR, levels = c("BMI", "EA", "height"), labels = c("BMI",  "EA", "height"))

# Set label (file with two columns: PHENO = short phenotype name used in above analyses; LABEL = phenotype name to be printed on the graph)
labels <- as.data.frame(fread("phenotype_labels.txt"))
df <- left_join(df, labels, by = "PHENO")

# Remodel in long format for ggplot & define phenotype order by decreasing forward effect
df_forest_forward <- df[, c(1:4, 6:8, 13:14)]
df_forest_forward$DIRECTION <- "forward"
colnames(df_forest_forward)[c(5:7)] <- c("ALPHA", "SE", "P")
ordered_pheno <- df_forest_forward[order(df_forest_forward$ALPHA, decreasing = F), "LABEL"]

df_forest_reverse <- df[, c(1:4, 10:14)]
df_forest_reverse$DIRECTION <- "reverse"
colnames(df_forest_reverse)[c(5:7)] <- c("ALPHA", "SE", "P")

df_forest <- rbind(df_forest_forward, df_forest_reverse)
rm(df_forest_forward, df_forest_reverse)

# Factorize MR direction
df_forest$DIRECTION <- factor(df_forest$DIRECTION)

# Factorize labels
df_forest$LABEL <- factor(df_forest$LABEL, levels = unique(ordered_pheno))

# Set size/transparency based on significance
df_forest$SIG <- "no"
df_forest[which(df_forest$P <= 0.05/(2*nrow(df))), "SIG"] <- "yes"
df_forest$SIG <- factor(df_forest$SIG, levels = c("yes", "no"))



########################################################
# STEP 4: Forest plot
########################################################

# Plot
p_forest <- ggplot(data = df_forest) +
            # Background
            geom_stripes(aes(y = LABEL), odd = "#F4F4F4", even = "white") + 
            geom_vline(xintercept = 0, color = "#2B4050", linewidth = 0.8, lty = "dashed") +
            # Effect
            geom_effect(aes(x = ALPHA, y = LABEL, xmin = ALPHA - 1.96*SE, xmax = ALPHA + 1.96*SE, colour = DIRECTION, alpha = SIG),
                        position = ggstance::position_dodgev(height = 0.5), size = 0.75) +
            scale_color_manual("MR effect", values = c(met.brewer("Demuth", 10)[3], met.brewer("Demuth", 10)[9]), drop = F) +
            scale_alpha_manual("Significant", values = c(1, 0.35), drop = F) +
            # Facet
            facet_grid(MEDIATOR~., scales = "free", space = "free", switch = "y") +
            scale_y_discrete(position = "right") +
            # Axis
            xlab("MR causal effect ± 95% CI") + ylab("") +
            coord_cartesian(xlim = c(-0.35, 0.65)) +
            scale_x_continuous(breaks = seq(-0.3, 0.6, 0.15), labels = c(-0.3, -0.15, 0, 0.15, 0.3, 0.45, 0.6)) +
            # Layout
            theme_bw() +
            theme(text = element_text(family = "Arial"),
                  axis.text.x = element_text(size = 9),
                  axis.title.x = element_text(size = 12, margin = margin(t = 7, r = 0, b = 0, l = 0)),
                  axis.text.y = element_text(size = 9),
                  legend.title = element_text(size = 12, face = "bold"),
                  legend.text = element_text(size = 11),
                  legend.position = "left", 
                  strip.text.y.left = element_text(size = 11, color = "#2B4050", face = "bold",  angle = 0),
                  strip.background = element_rect(fill = "#F4F4F4", color = "#2B4050")) +
            guides(colour = guide_legend(override.aes = list(size = 3))) +
            guides(alpha = guide_legend(override.aes = list(size = 3)))
          
# Save plot
showtext_auto()   
p_forest
ggsave("/plot/MR_forward_reverse.pdf", width = 7.3, height = 4.7)
showtext_auto(FALSE)